prefix: "<bold><gold>Better</gold><white>Ban</white></bold> <dark_gray>>></dark_gray> "

Sentence-notice:
  enable: true
  text: |-
    ----- <bold><gold>Better</gold><white>Ban</white></bold> -----
    <gold>处理者</gold> <dark_gray>>></dark_gray> <white>%executor%</white>
    <gold>封禁玩家</gold> <dark_gray>>></dark_gray> <white>%executed%</white>
    <gold>解封日期</gold> <dark_gray>>></dark_gray> <white>%time%</white>
    <gold>原因</gold> <dark_gray>>></dark_gray> <white>%reason%</white>

help:
  - "<white>----- <gold>Better</gold><white>Ban</white> <yellow>帮助</yellow> -----</white>"
  - "<gold>/ban</gold> <gray>或</gray> <gold>/bb</gold> <gray><玩家></gray> <gray><时间></gray> <yellow>[原因]</yellow> <white>- 封禁玩家</white>"
  - "<gold>/banlist</gold> <gray>或</gray> <gold>/bblist</gold> <yellow>[页码]</yellow> <white>- 查看封禁列表</white>"
  - "<gold>参数 <yellow>time</yellow> 说明:</gold>"
  - "<gold>d:</gold> <gold>后接日期 格式为</gold> <yellow>年/月/日</yellow>"
  - "<green>例子</green><gray>:</gray> <green>2000/1/1</green>"
  - "<gold>l:</gold> <gold>后接时长 格式为</gold> <yellow>数字单位</yellow>"
  - "<green>例子</green><gray>:</gray> <green>1s 1m 1h 1d</green>"
  - "<gold>forever</gold> <yellow>永封</yellow>"
  - "<white>----- <yellow>By</yellow> <gold>Noctiro</gold> -----</white>"

reason: |-
  <gold>米</gold><white>客</white>
  <gray>-------------------</gray>
  <red>你已被服务器封禁</red>
  <yellow>原因</yellow>
  <yellow>%reason%</yellow>
  <red>解封日期: %time%</red>
  如有异议 在QQ群1138627074向管理员申诉
  <gray>-------------------</gray>

